#!/usr/bin/with-contenv sh
set -e
set +x

CONSUL_URL=${CONSUL_URL:-consul.service.consul:8500}

if [ -n "$FILECONSUL_PREFIX" -a -n "$FILECONSUL_BASEPATH" ]; then
    status=`fileconsul status --addr $CONSUL_URL --prefix $FILECONSUL_PREFIX --basepath $FILECONSUL_BASEPATH 2>&1`
    if [ -n "$status" ]; then
        pull=`fileconsul pull --addr $CONSUL_URL --prefix $FILECONSUL_PREFIX --basepath $FILECONSUL_BASEPATH 2>&1`
        if [ $? -eq 0 ]; then
          nginx -s reload
        fi
    fi
fi
