#!/usr/bin/with-contenv sh
set -e

CONSUL_URL=${CONSUL_URL:-consul.service.consul:8500}
NGINX_CONFD=/etc/nginx/conf.d

if [ -d /etc/consul-templates ]; then
    for TEMPLATE in `ls /etc/consul-templates/*.conf`; do
      CONF="$NGINX_CONFD/`basename $TEMPLATE`"
      rm -f $NGINX_CONFD/default.conf
      exec consul-template \
           -consul=${CONSUL_URL} \
           -template "${TEMPLATE}:${CONF}:nginx -s reload"
      echo "Reloading Nginx with configuration : $CONF"
    done
fi