#!/usr/bin/with-contenv sh
set -e

CONSUL_URL=${CONSUL_URL:-localhost:8500}

if [ -d /etc/consul-template/conf ]; then
  exec consul-template \
       -consul ${CONSUL_URL} \
       -config "/etc/consul-template/conf"
fi